AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: Please Enter RDS Name
  TopicName:
    Type: String
    Description: Please Enter SNS topic name
  EC2InstanceID:
    Type: String
    Description: Please Enter EC2 Instance ID
  EmailId:
    Type: String
    Description: Please Enter EC2 Instance ID


Resources:
  SNSTopicInfo:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: !Ref TopicName
      TopicName: !Ref TopicName
      Subscription: 
        - Endpoint: !Ref EmailId
          Protocol: email
  

  CloudWatchAlarmRebootInstance:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: ["arn:aws:automate:ap-southeast-1:ec2:reboot", !Ref SNSTopicInfo]
      AlarmDescription: Money Plant Ec2 Health Check Alarm
      AlarmName: MoneyPlantInstanceReboot
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '2'
      MetricName: StatusCheckFailed
      Namespace: AWS/EC2
      Period: '60'
      Statistic: Average
      Threshold: '1'
      Dimensions:
      - Name: InstanceId
        Value: !Ref EC2InstanceID

  CloudWatchAlarmDIskUsage:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref SNSTopicInfo]
      AlarmDescription: MoneyPlant RDS DISK USAGE ALRAM
      AlarmName: MoneyPlantDiskUtilizationAlarm
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: '1'
      MetricName: FreeStorageSpace
      Namespace: AWS/RDS
      Period: '60'
      Statistic: Average
      Threshold: '10'
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DBInstanceIdentifier


  CloudWatchAlarmCpuUsage:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref SNSTopicInfo]
      AlarmDescription: MoneyPlant RDS CPU USAGE ALRAM
      AlarmName: MoneyPlantCPUUtilizationAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '1'
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Period: '300'
      Statistic: Average
      Threshold: '70'
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DBInstanceIdentifier

  CloudWatchAlarmDbConnections:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref SNSTopicInfo]
      AlarmDescription: MoneyPlant RDS DB CONNECTIONS ALRAM
      AlarmName: MoneyPlantDatabaseConnections
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: '1'
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Period: '300'
      Statistic: Average
      Threshold: '50'
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DBInstanceIdentifier

  CloudWatchAlarmFreeMemoey:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions: [!Ref SNSTopicInfo]
      AlarmDescription: MoneyPlant RAM UTILIZATION ALRAM
      AlarmName: MoneyPlantFreeMemory
      ComparisonOperator: LessThanOrEqualToThreshold
      EvaluationPeriods: '1'
      MetricName: FreeableMemory
      Namespace: AWS/RDS
      Period: '300'
      Statistic: Average
      Threshold: '1'
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref DBInstanceIdentifier


